# Setup
title:        Baiting's Homepage
tagline:      Welcome to my homepage!
baseurl:      "/jekyll-cayman-theme"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Baiting Xie
  url:        https://xiebaiting.github.io/math 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown